export enum ESkill {
    ATHLETICS = 'athletics',
    ACROBATICS = 'acrobatics',
    SLEIGHT_OF_HAND = 'sleight of hand',
    STEALTH = 'stealth',
    ARCANA = 'arcana',
    HISTORY = 'history',
    INVESTIGATION = 'investigation',
    NATURE = 'nature',
    RELIGION = 'religion',
    ANIMAL_HANDLING = 'animal handling',
    INSIGHT = 'insight',
    MEDICINE = 'medicine',
    PERCEPTION = 'perception',
    SURVIVAL = 'survival',
    DECEPTION = 'deception',
    INTIMIDATION = 'intimidation',
    PERFORMANCE = 'performance',
    PERSUASION = 'persuasion'
}
